### ISSUE TITLE
OTP test suite fails

### ISSUE THREAD

**Issue by gijzelaerr** [eduvpn-debian/packaging#1]
```
cp debian/autoload_test.php vendor/autoload.php
phpunit
PHP Fatal error:  Uncaught Error: Call to a member function add() on integer in /home/gijs/Work/eduvpn/otp/tests/bootstrap.php:4
Stack trace:
#0 /usr/share/php/PHPUnit/Util/Fileloader.php(56): include_once()
#1 /usr/share/php/PHPUnit/Util/Fileloader.php(38): PHPUnit_Util_Fileloader::load('/home/gijs/Work...')
#2 /usr/share/php/PHPUnit/TextUI/Command.php(875): PHPUnit_Util_Fileloader::checkAndLoad('/home/gijs/Work...')
#3 /usr/share/php/PHPUnit/TextUI/Command.php(704): PHPUnit_TextUI_Command->handleBootstrap('/home/gijs/Work...')
#4 /usr/share/php/PHPUnit/TextUI/Command.php(124): PHPUnit_TextUI_Command->handleArguments(Array)
#5 /usr/share/php/PHPUnit/TextUI/Command.php(113): PHPUnit_TextUI_Command->run(Array, true)
#6 /usr/bin/phpunit(29): PHPUnit_TextUI_Command::main()
#7 {main}
  thrown in /home/gijs/Work/eduvpn/otp/tests/bootstrap.php on line 4
```

**Comment by gijzelaerr** [comment]
is solved in current package.
